### ISSUE TITLE
Flags not allowing already existing buckets

### ISSUE THREAD

**Issue by jordanlambrecht** [juliankrispel/s3-auto-sync#6]
Typing in this command: `s3-auto-sync --region us-east-2 -d public -b cdn.redacted.com` results in the following error:

```
/Users/redacted/redacted/node_modules/aws-sdk/lib/services/s3.js:711
      resp.error = AWS.util.error(new Error(), {
                                  ^

BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
    at Request.extractError (/Users/redacted/redacted/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/Users/redacted/redacted/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/redacted/redacted/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/redacted/redacted/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/redacted/redacted/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/redacted/redacted/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/redacted/redacted/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/redacted/redacted/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/redacted/redacted/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/redacted/redacted/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'BucketAlreadyOwnedByYou',
  region: 'us-east-2',
  time: 2022-07-13T08:48:07.756Z,
  requestId: '9JDZX7HQ54GYRYCV',
  extendedRequestId: 'LlLquqNuKWAydpw27zD8M3IRZRDNrvRAGvTL8wAZaS9omwCRYcb5495cPRKtsHSLS31+ObfObSg=',
  cfId: undefined,
  statusCode: 409,
  retryable: false,
  retryDelay: 52.02005899237741
}

Node.js v18.5.0
error Command failed with exit code 1.
```

**Comment by bladx** [comment]
Related to [https://github.com/juliankrispel/s3-auto-sync/issues/2](https://github.com/juliankrispel/s3-auto-sync/issues/2)

**Comment by bladx** [comment]
I just made a PR to fix this issue: https://github.com/juliankrispel/s3-auto-sync/pull/7
Hope @juliankrispel will review it soon and release a new version that patches it!
